



var i8n={

cancel:"Cancel",
dec:"Dec",
temporarilyClosed:"(Temporarily Closed)",
noticeUnderMinCredits:"Notice: This schedule contains {} credits. You need {} or more credits for full-time.",
pinnedDownClass:"You pinned-down a class that is ",
xOnline:"is online",
examschedule:"Exam Schedule",
mostHomeCampus:"Most at home campus {}",
pinRegistrationMessage:"Please enter your registration PIN to continue:",
tipUseArrows:"Press the <strong>arrow keys</strong> to navigate your generated schedule results more quickly.",
campusesLC:" campuses",
classesSelfConflict:"classes self-conflict",
doesNotoccurLocations:"The selected class does not occur within the selected locations.",
sendToWorksheet:"Send CRNs to my Worksheet",
requestedClassNotOffered:"The requested class {} is not available or not offered at the selected location(s).",
exam:"Exam",
buildingAndRoomNo:"Building and Room Number",
dropCrns:"You would need to drop the following CRNs to get this schedule: {}",
noTermEnroll:"Enrollment not enabled for this term.",
hideInstructionalMethodSelector:"Hide instruction mode selector",
alreadyAddedPlan:"Imported plan contains {}, but it is already added.",
jun2:"June",
clickToUnpin:"Click to unpin course",
step2TextExample:"Import courses by using an option below.",
tipClickToPin:"<strong>Click on classes</strong> to pin them down temporarily. This will narrow the number of results.",
xAsychronousOnline2:"are online classes with no scheduled times",
xAsychronousOnline:"is an online class with no scheduled times",
forInstructor:"for specific instructor",
addTimeToAvoid:"Add Personal Times",
warningNotAllclasses:"Warning: Not all classes ",
turnOnAccessibility:"Turn on accessibility features",
probablyOnCampus:"probably on campus so you get no results.",
crnHelpText:"To get the schedule shown, use these Class Numbers when you register.",
term:"Term",
close:"Close",
dec2:"December",
enrolled:"Enrolled",
selectAllSessions:"Select All Session",
sep:"Sep",
tipAllFullNoChange:"One of your courses only has full classes. Schedules containing full classes are not permitted.",
generateSchedulesTitle:"Click this to generate all the possible schedule results for the listed courses. This will send you to the Results region",
noClassesSatisfy:"No classes satisfy the corequisite requirements (See Class Remarks)",
defaultEnrollmentAppointmentLabel:"",
alreadyEnrolled:"(Already enrolled in this class)",
noneVisible:"None Visible",
register:"Register",
jul:"Jul",
thu:"Thu",
jun:"Jun",
tipClickAndDragMobile:"<strong>Touch, hold for a second, and drag</strong> to indicate when you do not want to have classes. Schedules that avoid these times will be prioritized.",
collegeMustSelectFirst:"A college must be selected first.",
addTime:"Add Time",
added:"Added ",
fullOrOnCampus:"probably closed or on campus so you get no results.",
recommendations:"Recommendations",
hideSimilarOptions:"Hide Similar Options",
adding:"Adding ",
notPassing:"not passing the filters and/or does not result in any possible conflict-free schedules.",
others:" others",
add:"Add",
list:"List",
numberBetweenAreSelectable:"<br/><br/>Numbers between parentheses () are selectable components such as Labs.",
getThisSchedule:"Get this Schedule",
unableToLoad:"Unable to load your enrollment state",
unscheduled:"(unscheduled)",
dropAndAdd:"Drop & Add",
validateShoppingCart:"Validate Shopping Cart",
allThe:"All",
enterToDeselect:"Press enter to deselect all classes",
dropCourse:"Drop Course",
noFavsFor:"None for {}",
back:"Back",
jan2:"January",
nonReservedS:"Non reserved seats available",
alreadyInShopping:"(Already in Shopping Cart)",
allOnCampusClassesOnly:"All courses have 'On Campus Classes Only' selected, therefore this checkbox does not apply",
personalCleared:"Personal times have been cleared.",
step1TextNone:"No terms are currently available for enrollment.",
loseData:"Changing the Term will clear this page. Continue?",
tipCreateShareLinkTitle:"Share",
schedule:"Schedule",
seeClassRemarks:"See Class Remarks",
waitlistable:"Wait Listed",
selClassO4e:" no longer open for enrollment",
notAllPassing:"not resulting in any possible conflict-free schedules.",
notFound:"not found",
allWithinColleges:"All %n within selected colleges",
imFilteredOutCourse:"This course has no {} classes {} {} with the selected instruction modes.",
hideLocationSelector:"Hide location selector",
xWaitlistableClassesAv:"{} wait listed classes available",
selClassNot:" not available",
select:"Select...",
swapNeededB2:"If you proceed, the selected class will be added to your Shopping Cart. You will then need to complete the swap in the Student Centre.",
noClasses:"No {} classes {} {} ",
tipClickAndDrag:"<strong>Click and drag</strong><span class='accessOnlyInline'>, or manually enter Personal Times</span> to indicate when you do not want to have classes. Schedules that avoid these times will be prioritized.",
noCoursesToLoad:"No courses to load from PeopleSoft",
cleardTimesToAvoid:"Cleared all personal times.",
automaticallyAddDropSwap:"Go to the confirmation page to review details",
fri:"Fri",
feb2:"February",
oct:"Oct",
stayEnrolledIn:"Stay enrolled in",
period:"Session",
selClassCore:" not available for this attribute",
tipRecommendNumbers:"You may recommend a schedule by clicking 'Recommend'. In the legend the first number is the number of students to whom the <strong>course</strong> has been recommended this term. The second number is the number of students to whom the <strong>class</strong> has been recommended this term.",
audited:"Audit",
isCourseRequirement:"This course has been marked as required by an advisor",
overlapsNotWantClasses:"This schedule overlaps personal time when you do not want to have classes. ",
cancelled:"Cancelled",
sat2:"Saturday",
waitlist:"Wait List",
importRec:"My Recommendations",
cohortRatingDesc:"Given the selected courses, this indicates the number of classes of this schedule that are associated to the same cohort, out of the maximum number of classes that could be taken belonging to the same cohort.",
welcomeTermActionTextBlocking:"The following item(s) must be resolved before proceeding:",
planToDrop:"Drop this course...",
occurAtSelectedSessions:"offered for the selected sessions. Classes are available for the following sessions: ",
notTermActivatedAdvising:"The student is not activated to enroll for this term.",
withdrawWarning:"Proceeding will cause a withdrawal.",
ofThe:"of the",
alreadyEnrolledFor:"{} already enrolled for this schedule",
isClassRequirement:"A specific class section of this course has been assigned to you by an advisor",
clickToRemove:"Click on this block to remove it",
addToCart:"Add to Cart",
campusMustBeSelectedFirst:"A campus must be selected first.",
mar:"Mar",
clickToPin:"Click to pin down course section.",
may:"May",
printSchedule:"Print Schedule",
showInstructionalMethodSelector:"Show instruction mode selector",
waitListNotice:"",
gotoFavoritesPage:"View to Favourites region",
removed:"Removed course",
alreadyAdded:"You already selected {}.",
youAre:"You are",
attributes:"Attributes: ",
waitlisted:"Wait Listed",
pinRegistrationLabel:"PIN based registration is enabled.",
droppedClass:"Dropped {}",
noClassesWithOpenSeats:"has no classes with open seats that do not conflict with this course",
removeCourseFromSearch:"Remove this course from the Search",
timezoneToShow:"",
seats:"Seats",
youAreNotSigned:"You are not signed in",
weeksliderlabel:"Displaying Week of",
noCampusesSelectedAbove:"No campuses are selected above. ",
all:"All",
tipRecommendNumbersTitle:"Recommend Schedule",
currentlyOnCriteriaPage:"You are currently viewing the Select Courses region",
swap:"Swap",
postActionItemsSubText:"",
tipOnCampusClassesOnly:"One of your courses is set to 'On campus classes only' and you are filtering out all schedules that contain classes that are on campus therefore you will always have no results. Check 'On campus classes', or go back and modify the Search criteria by changing the dropdown selection.",
probablyOnline:"probably online so you get no results.",
xUnscheduled2:"have no scheduled times",
theSelClass:"The selected class is {}",
showSelector:"Toggle selector",
swapInCart:"Swap in Cart",
clearTimesToAviod:"Clear all Personal Times",
noClassesXWPeriod:"This course has no {} classes {} {} in the selected session.",
cappDisclaimer:"",
allNWithin:"All %n within selected campuses",
credits:"Units",
and:" and ",
of:"of",
tipFiltersTitle:"Filtering",
tryOnlyClass:"Try all classes (1)",
crn:"Class Number",
decreaseAccessibility:"Disable Accessibility Features",
classesThatAre:" classes that are ",
onCampusClassesOnly:"Try on campus classes only",
aboveHaveSeatsAvailable:"have seats available.<br/>",
onlineClassesOnly:"Try online classes only",
clickToPinAria:"Click to pin down course section. Pinning a section will filter the schedule results to only contain schedules containing the pinned section until the pin is removed.",
fromShoppingCart:"from Shopping Cart",
radioTipForYellow:"Class is wait listed",
fullClosed:"Closed",
gotoResultsPage:"View the Generated Results region",
tue:"Tue",
tipAllFull:"One of your courses only has full classes and your filter is set to not include schedules containing full classes.",
radioTipForRed:"Class is closed",
unknownSeatAvailability:"<span>Unknown Seat Availability</span>",
tipOffCampus:"You are not permitting off-campus classes from being included in the results. Including 'Off-campus classes' may produce possible schedules.",
calssIsOnline:"Class is Online",
auditDisclaimer:"Disclaimer: This DegreeWorks Audit is not real-time and may not be up to date.",
theCourse:"The course",
jan:"Jan",
noMoreHonors:"There are no schedules that contain only honors classes. Uncheck 'Show Only Honors Schedules'",
doesNotOccurFilters:"The class you are enrolled in does not occur within the selected filters.",
ext:"_en",
cancelWarning:"Proceeding will cancel the course.",
apr:"Apr",
browseForCourses:"Advanced Course Search",
sendToShoppingCart:"Send Schedule to Shopping Cart",
tooManyCombinations:"The generated schedule results are truncated because the input is too broad. To ensure all results are considered, pin down or toggle off some of your preferred classes.",
selectPlanToContinue:"Select an assigned plan to continue:",
totalCreditsPostscript:"",
tipUseArrowsTitle:"Browse",
selClassCpn:" not in the selected period",
noApplicableClasses:"(No applicable classes)",
enroll:"Enroll",
tipUncheckOnlineOnCampusClasses:"If you hide both online and on campus classes then you will always have no results. Uncheck 'Online Classes' or 'On campus classes'.",
onlineClassesOnlyCheck:"All courses have 'Online Classes Only' or 'Learn on Demand Only' selected, therefore this checkbox does not apply.",
noPeriod:"Open Session",
apr2:"April",
crnHelpTextWhenAdvising:"The student you are advising must use these Class Numbers to get the schedule shown.",
tipCreateShareLink:"Use the '<strong>Share</strong>' button to generate a link that can be shared with friends or advisors.",
overlappingTimes:" held at overlapping times during the week.",
increaseAccessibility:"Increase Accessibility",
campusChange:"Warning: Campus change - ensure adequate travel time.",
sun:"Sun",
showSessions:"Show Session",
tryAllClasses:"Try all classes",
enrollmentAppointmentLabel:"Enrollment Appointment",
found:"Found",
selClassCsn:" not in the selected session",
noResults:"No Results",
waitlistFull1:"The limit of one student waiting has been reached",
turnOffAccessibility:"Turn off accessibility features",
tipClickAndDragTitle:"Personal Times",
showSimilarOptions:"Show {} Similar Options",
showCampusSelector:"Show campus selector",
classesFull:"All classes are full",
verifyInternetConnection:"Verify your internet connection and try again",
inShoppingCart:"In Shopping Cart",
bothHonorsNHonors:"If you hide both honors and non-honors schedules then you will always have no results",
notYetEnrolled:"{} not enrolled for this schedule.",
pleaseWait:" Please wait",
closed:"Closed",
enterToSelect:"Press enter to select all classes",
to:"to",
tipCourseConflict:"You have searched courses that are held at overlapping times during the week. Use the checkbox left of each course to toggle it on or off and explore your options.",
open:"Open",
campuses:"Campuses:",
sendToWorkSheetSubText:"",
overlapsPersonalTime:"Unfortunately <strong>all of these schedule results</strong> overlap the personal time when you do not want to have classes, but the first results have the least amount of overlap",
fri2:"Friday",
available:"Available",
registrationOptional:"<br/>(Registration Optional)",
notTermActivated:"You are not activated to enroll for this term.",
mon2:"Monday",
scheduleBlank:"The schedule is blank because<br/> there are no courses selected.",
tue2:"Tuesday",
results:"schedule results",
invalidOr:"User invalid or not term activated",
toImport:"Use 'Import my Course Queue' to import queued courses into your selected courses.",
firstScheduleResult:"The first schedule result does not.",
studentIs:"Student is",
selectElectiveCourseCustomMsg:"You have optional courses to be selected",
showSessionSelector:"Show session selector",
campus:"Campus: ",
mar2:"March",
welcomeTermActionText:"The following items(s) are not resolved:",
allsectionsAreFull:"All sections are full",
noWaitlistable:" (no wait listed classes available)",
periodDrop:"{}",
aug:"Aug",
selectAll:"Select All",
tipCheckOnlineClassesOnly:"One of your courses is set to 'Online classes only' and you are filtering out all schedules that contain online classes therefore you will always have no results. Check 'Online Classes', or go back and modify the Search criteria by changing the dropdown selection.",
selectAtleastOne:"Warning: You must select at least one honors class above<br/> for this to be an honors schedule.",
showLocationSelector:"Show location selector",
hideSessions:"Hide Session",
full:"Full",
drop:"Drop",
tipLearnOnDemandClassesOnly:"One of your courses is set to 'Learn on Demand classes only' and you are filtering out all schedules that contain online classes therefore you will always have no results. Check 'Online Classes', or go back and modify the Search criteria by changing the dropdown selection.",
takenTogether:"This course contains class sections that must be taken concurrently with {}. To get more schedule options, add {} to the list of courses.",
thisCourseHasNoClasses:"The campuses selected above do not offer {} classes {} {} for this course in {}.",
tipFilters:"Use the '<strong>FILTERS</strong>' button to filter out schedule results containing full classes, etc.",
selectAdditionalCampuses:"Select additional campuses where you wish to take this course:",
showSimilarOption:"Show {} Similar Option",
deselectAllInstructionalMethods:"Deselect All Instruction modes",
warningOffCampus:"Attention: One or more classes above are not on the main campus.",
totalCredits:"Total Units",
postHoldsSubText:"",
selectAllColleges:"Select All Colleges",
test_example:"There is a {} in the {} by {}.",
nov:"Nov",
xOnline2:"are online",
deselectAllSessions:"Deselect All Session",
alreadyAddedPlanEnrolled:"Imported plan contains {}, but you are already enrolled in this course.",
dropNeeded:"(Drop Needed)",
hideSessionSelector:"Hide session selector",
radioTipForGreen:"Class is open",
noArrangement:"Currently there is no arrangement of this course and {} such that there is an open seat in each.",
waitlistNone:"There is no wait list for this class",
keepCourse:"Keep this course",
imFilteredOutSelectedClass:"The selected class uses an instruction mode that is filtered out.",
currentlyOnResultsPage:"You are currently viewing the Results region",
notTermActivatedWithHold:"You are not activated to enroll for this term.",
importAarTitle:"Academic Advisement Report",
occurAtSelectedlocations:"occur only at the selected locations. Classes are at the following locations: ",
selectAllInstructionalMethods:"Select All Instruction modes",
fullOrOnline:"probably closed or online so you get no results.",
none:"None",
selfConflicting:"All classes of this course are self-conflicting",
mon:"Mon",
required:"Required",
recCSV:"The file to be converted into Recommendation(s) should contain following columns: <br> Student (EMPLID), Course/Section (Ex: MATH-101), Term (STRM), Title, and Description.",
authorized:"Authorized",
selectNone:"Select None",
instructionalMethods:"Instruction Modes",
oct2:"October",
sessions:"Session",
activeUserLogout:"Session expired",
notEnrolled:"Not Enrolled",
takenTogetherCourse:"This course must be taken concurrently with {}.",
removeFromShoppingCart:"Remove from Shopping Cart",
youPinnedDown:"You pinned-down ",
gotoCriteriaPage:"View the Select Courses region",
learnOndemanClassesOnly:"Try Learn on Demand classes only",
examples:"Examples: Friday 2-9pm, MW 8-10, Fri 15-17",
tipUseArrowsMobile:"<strong>Swipe left and right</strong> to navigate your generated schedule results more quickly.",
requestedClassCancelled:"The requested class {} is not available.",
classFull:"Class is full",
dontWant:"Click and drag to choose where you don't want classes",
theFirst:"The first",
otherCampusOpenClasses:"There are open classes of this at other campuses",
waitlistFull:"The limit of {} students waiting has been reached",
sun2:"Sunday",
cartDoesNotFilters:"The class in your shopping cart does not occur within the selected filters.",
youMustIncludeCampus:"You must include the campus where this class is offered this term:",
tipClickToPinMobile:"<strong>Tap on classes</strong> to pin them down temporarily. This will narrow the number of results.",
wed:"Wed",
currentlyOnFavoritesPage:"You are currently viewing the Favourites region",
aarErrorMessage:"Schedule Builder encountered an error attempting to retrieve your report.",
dwAuditImport:"DegreeWorks Audit",
dropNeeded2:"<strong>You are currently {} in this class.</strong> For your chosen schedule to work, drop this course in your Student Centre.",
may2:"May",
tipClickToPinTitle:"Pinning",
ScheduleAlreadyInCart:"This schedule is already in your Shopping Cart",
scheduleResultsDoNot:"schedule results do not.",
inShoppingCartL:"in Shopping Cart",
clearTimesToAviodText:"Click and drag on the schedule above, or enter a time range here to add it manually. Schedule results that avoid personal times will be prioritized.",
termHasCompulsory:"Your advisor has assigned a mandatory plan for this term. To proceed, start over and select the plan.",
ReviewExamples:"Could not understand input. Review examples.",
notDroppedUntil:"You have not finished dropping this course.",
stillOpenForEnrollement:"still open for enrollment ",
importCappPlanTitle:"CAPP Degree Plan",
stayWaitlistedIn:"Stay wait listed in",
wasAdded:"was selected",
feb:"Feb",
generatedResults:"Generated Results",
allPeriods:"All Sessions",
scheduleWarning:"",
wSelAttribute:"with this attribute",
noticeOverMaxCredits:"Notice: This schedule contains {} credits which is over the maximum of {}.",
activeUserConflict:"It looks like you already have this application running in another tab. To avoid discrepancy, please refresh the page.",
waitlistStatus:"{} wait list seats remaining",
swapNeededB:"(Swap Needed)",
allClassesHue:"This course does not have any classes {} {} available this term.",
swapNeeded:"(Swap Needed)",
instructionalMethod:"Instruction Mode",
sep2:"September",
chooseCampusToselectThisCourse:"To include this course, choose a campus where the course is still offered this term.",
wed2:"Wednesday",
checkoutEnroll:"Checkout (Enroll)",
core:"Attribute",
noDwPlanFor:"No degree plans found for {}",
xUnscheduled:"has no scheduled times",
instructor:"Instructor(s)",
timeblock:"timeblock",
keep:"Keep",
daylightSavingTimeMessage:"*Daylight Saving Time is observed. Therefore:<br/><br/>Fall classes will begin 1 hour earlier than indicated here until DST ends the 1st Sunday of November. <br/><br/>Spring classes will begin an hour earlier than indicated here after the 2nd Sunday in March when DST begins.",
apUnits:"Academic Progress Units",
chooseTerm:"You must choose a term first.",
studentCSV:"The file should contain a list of Student IDs in its first column.",
cannotEnroll:"Enrollment blocked at this time.",
timezone:"Timezone: ",
hideSelector:"Hide selector",
hideCampusSelector:"Hide campus selector",
nov2:"November",
changeSheduleFilter:"<br/><br/>Change your schedule filter or ",
advisorCannotRemoveFromShoppingCart:"Advisors are not permitted to modify an advisee's shopping cart",
electiveCourseSelectionWarning:"Please try a different elective option.",
jul2:"July",
noClassesSelected:"The course {} does not have any classes selected.",
sat:"Sat",
thu2:"Thursday",
colleges:"Colleges:",
welcomeActionSubText:"",
courseConflict:"All classes of this course conflict with all classes of",
schedulesFound:"schedule result{}",
recommended:"Recommended",
aug2:"August",
locations:"Locations:",
sessionLabel:"",
removethepins:"remove the pins",
};

// Example: i8n.s("test_example","cat","hat","seuss")
i8n.s = function(key,p0,p1,p2,p3,p4) {
	var str = (this.hasOwnProperty(key)) ? this[key] : key;
	var marker = "{}";
	for(var arg = 1; arguments.length > arg; arg++) str = str.replace(marker,arguments[arg]);
	return str;
}
